version: "2.1"
orbs:
  docker: circleci/docker@2.1.5
jobs:
  lint-dockerfile:
    executor: docker/machine
    steps:
      - checkout
      - docker/dockerlint:
          dockerfile: ./Dockerfile
          treat-warnings-as-errors: true

  test-app:
    docker:
      - image: golang:1.16
    working_directory: /go/src/github.com/dicodingacademy/karsajobs
    steps:
      - checkout
      - run: go test -v -short --count=1 $(go list ./...)
  
  build-app-karsajobs:
    executor: docker/machine
    steps:
      - checkout
      - run: 
          command: sh ./build_push_image_karsajobs.sh
          environment: 
            USERNAME_DOCKER_HUB: "<USERNAME CONTAINER REGISTER>"
            PASSWORD_DOCKER_HUB: "<PASSWORD CONTAINER REGISTER>"

workflows:
  circleci-said:
    jobs:
      - lint-dockerfile
      - test-app
      - build-app-karsajobs
